virtual const OSMetaClass * getMetaClass();
virtual bool isEqualTo(const OSMetaClassBase * anObject);
virtual bool init_1( OSDictionary * dictionary );
virtual void setPropertyTable( OSDictionary * dict );
virtual bool setProperty(const OSSymbol * aKey,OSObject * anObject);
virtual bool setProperty_1(const OSString * aKey, OSObject * anObject);
virtual bool setProperty_2(const char * aKey, OSObject * anObject);
virtual bool setProperty_3(const char * aKey, const char * aString);
virtual bool setProperty_4(const char * aKey, bool aBoolean);
virtual bool setProperty_5( const char * aKey,unsigned long long aValue,unsigned int aNumberOfBits);
virtual bool setProperty_6( const char * aKey,void * bytes,unsigned int length);
virtual void removeProperty( const OSSymbol * aKey);
virtual void removeProperty_1( const OSString * aKey);
virtual void removeProperty_2( const char * aKey);
virtual OSObject * getProperty( const OSSymbol * aKey);
virtual OSObject * getProperty_1( const OSString * aKey);
virtual OSObject * getProperty_2( const char * aKey);
virtual OSObject * getProperty_3( const OSSymbol * aKey,const IORegistryPlane * plane,IOOptionBits options);
virtual OSObject * getProperty_4( const OSString *aKey,const IORegistryPlane * plane,IOOptionBits options);
virtual OSObject * getProperty_5( const char *aKey,const IORegistryPlane * plane,IOOptionBits options);
virtual OSObject * copyProperty_2( const OSSymbol * aKey,const IORegistryPlane * plane );
virtual OSObject * copyProperty_1( const OSString * aKey,const IORegistryPlane * plane );
virtual OSObject * copyProperty( const char * aKey,const IORegistryPlane * plane );
virtual OSObject * copyProperty_3( const OSSymbol * aKey);
virtual OSObject * copyProperty_4( const OSString * aKey);
virtual OSObject * copyProperty_5( const char * aKey);
virtual OSDictionary *  dictionaryWithProperties( void );
virtual bool serializeProperties( OSSerialize * serialize );
virtual IOReturn setProperties( OSObject * properties );
virtual OSIterator * getParentIterator( const IORegistryPlane * plane );
virtual void applyToParents( void * applier,void * context,const IORegistryPlane * plane );
virtual IORegistryEntry * getParentEntry( const IORegistryPlane * plane );
virtual OSIterator * getChildIterator( const IORegistryPlane * plane );
virtual void applyToChildren( void * applier,void * context,const IORegistryPlane * plane );
virtual IORegistryEntry * getChildEntry( const IORegistryPlane * plane );
virtual bool isChild( IORegistryEntry * child,const IORegistryPlane * plane,bool onlyChild );
virtual bool isParent( IORegistryEntry * parent,const IORegistryPlane * plane,bool onlyParent);
virtual bool inPlane( const IORegistryPlane * plane);
virtual unsigned int getDepth( const IORegistryPlane * plane );
virtual bool attachToParent( IORegistryEntry * parent,const IORegistryPlane * plane );
virtual void detachFromParent( IORegistryEntry * parent,const IORegistryPlane * plane );
virtual bool attachToChild( IORegistryEntry * child,const IORegistryPlane * plane );
virtual void detachFromChild( IORegistryEntry * child,const IORegistryPlane * plane );
virtual void detachAbove( const IORegistryPlane * plane );
virtual void detachAll( const IORegistryPlane * plane );
virtual const char * getName( const IORegistryPlane * plane );
virtual const OSSymbol * copyName(const IORegistryPlane * plane);
virtual bool compareNames( OSObject * name, OSString ** matched );
virtual bool compareName( OSString * name, OSString ** matched);
virtual void setName( const OSSymbol * name,const IORegistryPlane * plane);
virtual void setName_1( const char * name,const IORegistryPlane * plane);
virtual const char * getLocation( const IORegistryPlane * plane);
virtual const OSSymbol * copyLocation(const IORegistryPlane * plane);
virtual void setLocation( const OSSymbol * location,const IORegistryPlane * plane );
virtual void setLocation_1( const char * location,const IORegistryPlane * plane);
virtual bool getPath( char * path, int * length,const IORegistryPlane * plane);
virtual bool getPathComponent( char * path, int * length,const IORegistryPlane * plane );
virtual IORegistryEntry * childFromPath( const char * path,const IORegistryPlane * plane,char * residualPath,int * residualLength );
virtual bool init_2( IORegistryEntry * from,const IORegistryPlane * inPlane );
virtual IORegistryEntry * copyParentEntry( const IORegistryPlane * plane );
virtual IORegistryEntry * copyChildEntry( const IORegistryPlane * plane );
virtual IOReturn runPropertyAction(void * action, OSObject *target,void *arg0 , void *arg1,void *arg2 , void *arg3);
virtual void free();