OSData * withData(OSData *inData, unsigned int start, unsigned int numBytes);
OSData * withData(OSData *inData);
OSData * withCapacity(unsigned int capacity);
OSData * withBytesNoCopy(void *bytes, unsigned int numBytes);
OSData * withBytes(void *bytes, unsigned int numBytes);
virtual bool initWithBytes(void *bytes, unsigned int numBytes);
virtual unsigned int getLength(void);
virtual unsigned int getCapacityIncrement(void);
virtual unsigned int getCapacity(void);
virtual unsigned int ensureCapacity(unsigned int newCapacity);
virtual bool initWithBytesNoCopy(void *bytes, unsigned int numBytes);
virtual bool initWithCapacity(unsigned int capacity);
virtual bool serialize(OSSerialize *serializer);
virtual void free();
virtual const OSMetaClass * getMetaClass();
virtual bool initWithData(const OSData * inData);
bool initWithData_1(const OSData *inData,unsigned int start, unsigned int inLength);
virtual unsigned int getLength();
virtual unsigned int getCapacity();
virtual unsigned int getCapacityIncrement();
virtual unsigned int setCapacityIncrement(unsigned increment);
virtual bool appendByte(unsigned char  byte, unsigned int numBytes);
virtual bool appendBytes(void *bytes,  unsigned int numBytes);
virtual bool appendBytes_1(const OSData * aDataObj);
virtual const void * getBytesNoCopy()
virtual void * getBytesNoCopy_1(unsigned int start, unsigned int numBytes);
virtual bool isEqualTo_1(const OSData * aDataObj);
virtual bool isEqualTo_2(const void   * bytes,unsigned int   numBytes);
virtual bool isEqualTo(const OSMetaClassBase * anObject);
virtual bool isEqualTo_3(const OSString * aString);
//typedef void (*DeallocFunction)(void * ptr, unsigned int length);
virtual void setDeallocFunction(void * func);

