OSSerialize * binaryWithCapacity(unsigned int inCapacity, void * editor, void *reference);
OSSerialize * withCapacity(unsigned int capacity);
virtual char * text(void);
virtual bool initWithCapacity(unsigned int inCapacity);
virtual void endBinaryCollection(uint32_t startCollection);
virtual void clearText(void);
virtual bool binarySerializeInternal(void *o);
virtual bool addString(char *cString);
virtual bool addBinaryObject(void *o, uint32_t key, void *_bits, size_t size, uint32_t *startCollection);
virtual bool addBinary(void *data, size_t size);
virtual bool previouslySerialized(const OSMetaClassBase *o);
virtual bool addXMLStartTag(const OSMetaClassBase * object,const char * tagString);
virtual bool addXMLEndTag(const char * tagString);
virtual bool addChar(const char aChar);
virtual bool addString(const char * cString);
virtual bool initWithCapacity(unsigned int inCapacity);
virtual unsigned int getLength();
virtual unsigned int getCapacity();
virtual unsigned int getCapacityIncrement() ;
virtual unsigned int setCapacityIncrement(unsigned increment);
virtual unsigned int ensureCapacity(unsigned int newCapacity);
virtual void free();
virtual const OSMetaClass * getMetaClass();
virtual bool isEqualTo(const OSMetaClassBase * anObject);